require './Pieces/piece.rb'
require './Pieces/bishop.rb'
require './Pieces/queen.rb'
require './Pieces/rook.rb'
require './Pieces/pawn.rb'
require './Pieces/knight.rb'
require './Pieces/king.rb'
require_relative "./Pieces/nullpiece.rb"
require "byebug"
require_relative "cursor.rb"
require "colorize"